variables:
  PYTHON_ENVIRONMENT_PATH: $CI_BUILDS_DIR/MuyGPyS

stages:
  - environment
  - test

.template_run_rules:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
    
configure_python:
  extends: .template_run_rules
  stage: environment
  tags:
    - quartz
    - shell
  script:
    - if [ ! -d "${PYTHON_ENVIRONMENT_PATH}" ]; then
        /usr/tce/bin/virtualenv -p /usr/tce/bin/python3-3.8.2 ${PYTHON_ENVIRONMENT_PATH}
      fi
    - source ${PYTHON_ENVIRONMENT_PATH}/bin/activate
    - pip uninstall MuyGPyS
    - pip install -e .
    
.template_env_load:
  before_script:
    - source ${PYTHON_ENVIRONMENT_PATH}/bin/activate

test_data:
  extends: .template_run_rules
  extends: .template_env_load
  stage: test
  tags:
    - quartz
    - shell
  script:
    - python tests/data.py

test_gp:
  extends: .template_run_rules
  extends: .template_env_load
  stage: test
  tags:
    - quartz
    - shell
  script:
    - srun -N1 -ppdebug -A madstare python tests/gp.py

test_neighbors:
  extends: .template_run_rules
  extends: .template_env_load
  stage: test
  tags:
    - quartz
    - shell
  script:
    - python tests/neighbors.py

test_optimize:
  extends: .template_run_rules
  extends: .template_env_load
  stage: test
  tags:
    - quartz
    - shell
  script:
    - srun -N1 -ppdebug -A madstare python tests/optimize.py

test_predict:
  extends: .template_run_rules
  extends: .template_env_load
  stage: test
  tags:
    - quartz
    - shell
  script:
    - srun -N1 -ppdebug -A madstare python tests/predict.py

test_multivariate:
  extends: .template_run_rules
  extends: .template_env_load
  stage: test
  tags:
    - quartz
    - shell
  script:
    - python tests/multivariate.py

test_api_mnist:
  extends: .template_run_rules
  extends: .template_env_load
  stage: test
  tags:
    - quartz
    - shell
  script:
    - srun -N1 -ppdebug -A madstare python tests/api.py MNISTTest /p/lustre1/madstare/muygps-data/

test_api_stargal:
  extends: .template_run_rules
  extends: .template_env_load
  stage: test
  tags:
    - quartz
    - shell
  script:
    - srun -N1 -ppdebug -A madstare python tests/api.py StargalTest /p/lustre1/madstare/muygps-data/

test_api_heaton:
  extends: .template_run_rules
  extends: .template_env_load
  stage: test
  tags:
    - quartz
    - shell
  script:
    - srun -N1 -ppdebug -A madstare python tests/api.py HeatonTest /p/lustre1/madstare/muygps-data/
