variables:
  PYTHON_ENVIRONMENT_PATH: $CI_BUILDS_DIR/python-muyscans

stages:
  - environment
  - test

configure_python:
  stage: environment
  tags:
    - quartz
    - shell
  script:
    - virtualenv --python=/usr/tce/bin/python3-3.8.2 ${PYTHON_ENVIRONMENT_PATH}
    - source ${PYTHON_ENVIRONMENT_PATH}/bin/activate
    - pip install -r requirements.txt
    - pip install -e .
    - python -c "import muyscans"

.template_env_load:
  before_script:
    - source ${PYTHON_ENVIRONMENT_PATH}/bin/activate

test_data:
  extends: .template_env_load
  stage: test
  tags:
    - quartz
    - shell
  script:
    - python test/data.py