image: "python:3.8"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - /usr/tce/bin/virtualenv --python=/usr/tce/bin/python3-3.8.2 venv
  - source venv/bin/activate
  - source scripts/lc-setup/pascal.sh
  - which python
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade jax[cuda11_cudnn805] -f https://storage.googleapis.com/jax-releases/jax-releases.html
  - pip install -e .[tests,mpi]

all_tests:
  stage: test
  tags:
    - pascal
    - shell
  script:
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/data.py --muygpys_mpi_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/neighbors.py --muygpys_mpi_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/kernels.py --muygpys_mpi_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/gp.py --muygpys_mpi_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/optimize.py --muygpys_mpi_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/predict.py --muygpys_mpi_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/multivariate.py --muygpys_mpi_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/jax_correctness.py --muygpys_mpi_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/api.py /p/lustre1/madstare/muygps-data/ --muygpys_mpi_enabled=False
    - echo "done with JAX tests"
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/kernels.py --muygpys_jax_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/gp.py --muygpys_jax_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/optimize.py --muygpys_jax_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/predict.py --muygpys_jax_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/multivariate.py --muygpys_jax_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/jax_correctness.py --muygpys_jax_enabled=False
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/api.py /p/lustre1/madstare/muygps-data/ --muygpys_jax_enabled=False
    -echo "done with MPI tests"
