stages:
  - build
  - test
  - teardown

build_build:
  stage: build
  tags:
    - quartz
    - shell
  script:
    - virtualenv --python=/usr/tce/bin/python3-3.8.2 --no-site-packages test_env
    - source test_env/bin/activate

test_test:
  stage: test
  needs: [build_build]
  tags:
    - quartz
    - shell
  script:
    - pip list