image: "python:3.8"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
      when: always
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: always

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - /usr/tce/bin/virtualenv --python=/usr/tce/bin/python3-3.8.2 venv
  - source venv/bin/activate
  - source scripts/lc-setup/pascal.sh
  - which python
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade jax[cuda11_cudnn805] -f https://storage.googleapis.com/jax-releases/jax-releases.html
  - pip install -e .[tests,hnswlib,mpi]
  - pip install torch

all_tests:
  stage: test
  tags:
    - pascal
    - shell
  script:
    - export MUYGPYS_BACKEND=jax
    - echo "performing JAX tests"
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/data.py
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/neighbors.py
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/kernels.py
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/gp.py
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/scale_opt.py
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/optimize.py
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/predict.py
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/multivariate.py
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/backend/jax_correctness.py
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/api/regress.py /p/lustre1/madstare/muygps-data/
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/api/classify.py /p/lustre1/madstare/muygps-data/
    - salloc -N1 -ppvis -A muygps --mpibind=on python tests/precompute/fast_regress_api.py /p/lustre1/madstare/muygps-data/
    - echo "done with JAX tests"
    - export MUYGPYS_BACKEND=mpi
    - echo "performing MPI tests"
    - salloc -N1 --tasks-per-node=36 -ppvis -A muygps --mpibind=on python tests/kernels.py
    - salloc -N1 --tasks-per-node=36 -ppvis -A muygps --mpibind=on python tests/gp.py
    - salloc -N1 --tasks-per-node=36 -ppvis -A muygps --mpibind=on python tests/scale_opt.py
    - salloc -N1 --tasks-per-node=36 -ppvis -A muygps --mpibind=on python tests/optimize.py
    - salloc -N1 --tasks-per-node=36 -ppvis -A muygps --mpibind=on python tests/predict.py
    - salloc -N1 --tasks-per-node=36 -ppvis -A muygps --mpibind=on python tests/multivariate.py
    - salloc -N1 --tasks-per-node=36 -ppvis -A muygps --mpibind=on python tests/backend/mpi_correctness.py
    - salloc -N1 --tasks-per-node=36 -ppvis -A muygps --mpibind=on python tests/api/regress.py /p/lustre1/madstare/muygps-data/
    - salloc -N1 --tasks-per-node=36 -ppvis -A muygps --mpibind=on python tests/api/classify.py /p/lustre1/madstare/muygps-data/
    - echo "done with MPI tests"
    - export MUYGPYS_BACKEND=torch
    - echo "performing Torch tests"
    - salloc -N1 --tasks-per-node=36 -ppvis -A muygps --mpibind=on python tests/backend/torch_correctness.py
    - salloc -N1 --tasks-per-node=36 -ppvis -A muygps --mpibind=on python tests/torch/torch_api.py /p/lustre1/madstare/muygps-data/
    - echo "done with Torch tests"
