image: "python:3.8"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - /usr/tce/bin/virtualenv --python=/usr/tce/bin/python3-3.8.2 venv
  - source venv/bin/activate
  - source scripts/lc-setup/pascal.sh
  - which python
  - python --version
  - pip install --upgrade pip
  - pip install -e .[tests]
  - pip install --upgrade jax[cuda11_cudnn805] -f https://storage.googleapis.com/jax-releases/jax-releases.html

all_tests:
  stage: test
  tags:
    - pascal
    - shell
  script:
    - salloc -N1 -ppvis -A muygps
    - python tests/data.py
    - python tests/neighbors.py
    - python tests/kernels.py
    - python tests/gp.py
    - python tests/optimize.py
    - python tests/predict.py
    - python tests/multivariate.py
    - python tests/versions.py
    - python tests/api.py /p/lustre1/madstare/muygps-data/
