stages:
  - test

test_test:
  stage: test
  tags:
    - quartz
    - shell
  script:
    - virtualenv --python=/usr/tce/bin/python3-3.8.2 test_env
    - source test_env/bin/activate
    - pip list
    - pwd